update dependencies, kustomize deploy & add cors
Informasjonsforvaltning/catalog-comments-service pull request #121
Opened 2024-11-25 09:32 UTC by NilsOveTen

2024-11-25 22:20 UTC, valosnah requested changes

2024-11-25 22:20 UTC, valosnah commented on deploy/base/catalog-comments-service-deployment.yaml
> +              memory: "2Gi"
Memory request og limit burde være like

2024-11-26 14:11 UTC, torleifg approved these changes

2024-11-26 17:21 UTC, valosnah approved these changes

2024-11-27 08:28 UTC, merged